<?php

namespace Ghyneck\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GpxfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GpxfileRepository extends EntityRepository
{
}
