<?php

namespace Ghyneck\MapBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TourRepository extends EntityRepository
{
    
    public function findAll()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM MapBundle:Tour t'
            )
            ->getResult();
    }
}
