map_tour:
    resource: "@MapBundle/Resources/config/routing/tour.yml"
    prefix:   /tour

map_tourimage:
    resource: "@MapBundle/Resources/config/routing/tourimage.yml"
    prefix:   /tourimage

map_homepage:
    path:     /
    defaults: { _controller: MapBundle:Default:index }
