Ghyneck\MapBundle\Entity\Tour:
    properties:
        gpxfile:            
            - Valid: ~                
Ghyneck\MapBundle\Entity\Gpxfile:
    properties:                
        file:
            - File:
                mimeTypes: [application/xml]                
                maxSize: 5M