# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  app.twig_extension:
    class: Ghyneck\MapBundle\Twig\MapExtensions
    public: false
    tags:
      - { name: twig.extension }
  fileImporter:
    class: Ghyneck\MapBundle\Service\FileImporter
    arguments: ['@service_container']
    tags:
      - { name: doctrine.event_listener, event: prePersist }
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
