Ghyneck\MapBundle\Entity\Category:
    type: entity
    table: null
    repositoryClass: Ghyneck\MapBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    lifecycleCallbacks: {  }
    oneToMany:
            tours:
                targetEntity: Tour
                mappedBy: category
