Ghyneck\MapBundle\Entity\Gpxfile:
    type: entity
    table: null
    repositoryClass: Ghyneck\MapBundle\Entity\GpxfileRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        filename:
            type: string
            length: 255   
        clientOriginalFileName:
            type: string
            length: 255
    #oneToOne:
    #    tour:
    #        targetEntity: Tour   
    #        cascade: [all]
    lifecycleCallbacks:
        prePersist: [ preUpload ]
        postPersist: [ upload ]
        preUpdate: [ preUpload ]    
        postUpdate: [ upload ]
        preRemove: [ removeUpload ]
