Ghyneck\MapBundle\Entity\Product:
    type: entity
    table: null
    repositoryClass: Ghyneck\MapBundle\Entity\ProductRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: '100'
        price:
            type: decimal
        description:
            type: text
    manyToOne:
        category:
            targetEntity: Category
            inversedBy: products
            joinColumn:
                name: category_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
