Ghyneck\MapBundle\Entity\Tour:
    type: entity
    table: null
    repositoryClass: Ghyneck\MapBundle\Entity\TourRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
        description:
            type: text
        gpxFileName:
            type: string
            length: 255
        markerlat:
            type: float
        markerlon:
            type: float
    oneToMany:
        tourImages:
            targetEntity: TourImage
            mappedBy:     tour
            cascade:      ["persist", "merge"]
    manyToOne:
            category:
                targetEntity: Category
                inversedBy: tours
                joinColumn:
                    name: category_id
                    referencedColumnName: id
    lifecycleCallbacks: {  }
