tour:
    path:     /
    defaults: { _controller: "MapBundle:Tour:index" }

tour_show:
    path:     /{id}/show
    defaults: { _controller: "MapBundle:Tour:show" }

tour_new:
    path:     /new
    defaults: { _controller: "MapBundle:Tour:new" }

tour_create:
    path:     /create
    defaults: { _controller: "MapBundle:Tour:create" }
    methods:  POST

tour_edit:
    path:     /{id}/edit
    defaults: { _controller: "MapBundle:Tour:edit" }

tour_update:
    path:     /{id}/update
    defaults: { _controller: "MapBundle:Tour:update" }
    methods:  [POST, PUT]

tour_delete:
    path:     /{id}/delete
    defaults: { _controller: "MapBundle:Tour:delete" }
    methods:  [POST, DELETE]
